'''
Class which defines selection menus where the menu is generated by a tree
'''

from abc import ABC, abstractmethod
from textual_oks.data_structures.configuration_handler import ConfigurationHandler
from textual_oks.data_structures.relational_graph import RelationalGraph

class SelectionInterface(ABC):
    ''' Generic Selection interface
    '''
    def __init__(self, config_handler: ConfigurationHandler):
        self._handler = config_handler
        self._relational_dict: dict = self._build_relational_dict()
    
    def recompose(self)->None:
        self._relational_dict = self._build_relational_dict()
    
    @abstractmethod
    def _build_relational_dict(self):
        return {}
    
    @property
    def relationships(self):
        return self._relational_dict
    
    
# Couple of concrete classes
class ClassSelectionMenu(SelectionInterface):
    '''Selection menu based purely on the class of objects
    '''
    def _build_relational_dict(self):
        return self._handler.get_all_conf_classes()
    
    def __repr__(self):
        return "ClassSelectionMenu"
    
class RelationalSelectionMenu(SelectionInterface):
    ''' Selection menu based on class relationships
    '''    
    def _build_relational_dict(self):
        self._relational_graph = RelationalGraph(self._handler)
        
        configuration_dict = {f"[green]Sessions" : [self.__build_node(top_node) for top_node in self._relational_graph.top_level_nodes if top_node.className() == "Session"],
                        f"[green]Objects outside of Session" : [self.__build_node(top_node) for top_node in self._relational_graph.top_level_nodes if top_node.className() != "Session"]}
        
        return configuration_dict
    
    def __build_node(self, conf_obj):
        relationships = self._handler.get_relationships_for_conf_object(conf_obj)
        
        if not len(relationships):
            return conf_obj
        
        return {conf_obj: [self.__build_node(rel) for rel in relationships]}
    
    def __repr__(self):
        return "RelationalSelectionMenu"