#!/bin/env python3

import click
from rich import print
from daqconf.managed_component_manager import ManagedComponentManager, ManagedComponentPrinter


@click.command()
@click.option('--oksfile', '-f', required=True, help="Path to top level OKS file containing a Session")
@click.option('--session_name', '-s', required=True, help="Session name in the OKS file")
@click.option('--show_disabled', '-d', default=False, is_flag=True, help="Show all managed components in the configuration, even disabled ones")
def check_managed_components(oksfile, session_name, show_disabled):
    '''
    Script to check managed components satisfy the following:
        - They are not nested
    '''
    print(f"[bold]Checking {oksfile} for managed components")
    
    manager = ManagedComponentManager(oksfile, session_name)
    printer = ManagedComponentPrinter(manager)
    
    printer.print_managed_components(show_disabled)
    printer.print_nested_components()
    
if __name__=="__main__":
    check_managed_components()