#!/bin/env python3
import click
from daqconf.consolidate import consolidate_db
from daqconf.utils import log_levels, setup_logging

@click.command()
@click.option('--oksfile', '-i', help='Input database to read')
@click.option('--log-level', '-l', help='Log level', default='INFO', type=click.Choice(log_levels, case_sensitive=False))
@click.argument('output_file')
@click.option('--session', '-s', help='Session ID', default=None)
def consolidate(oksfile, output_file, log_level, session):
    setup_logging(log_level)
    consolidate_db(oksfile, output_file, session)

if __name__ == '__main__':
    consolidate()
