#!/bin/env python3
import click
import pathlib
from daqconf.consolidate import copy_configuration

@click.command()
@click.argument('output_directory', type=click.Path(exists=True), nargs=1)
@click.argument('databases', nargs=-1)
def copy_config(output_directory, databases):
    """Copy to OUTPUT_DIRECTORY configuration represented by DATABASES"""
    copy_configuration(pathlib.Path(output_directory), databases)  

if __name__ == '__main__':
    copy_config()
