#!/bin/env python3
import conffwk
import confmodel

import click
import os
import glob
from daqconf.set_session_env_var import set_session_env_var

@click.command()
@click.option('--session_name', '-s', type=str, default='',
              help='Name of session to manipulate if not specified the first '
              'session found in the database will be used')
@click.argument('oksfile')
@click.argument('env_var_name', required=True, nargs=1)
@click.argument('env_var_value', required=True, nargs=1)
def oks_set_session_env_var(oksfile, env_var_name, env_var_value, session_name):
  """Script to set the value of an environment variable in the specified Session of the
  specified OKS database file"""
  set_session_env_var(oksfile, env_var_name, env_var_value, session_name)

if __name__ == '__main__':
  oks_set_session_env_var()
