#!/bin/env python3
import conffwk
import confmodel

import click
import os
import glob
from daqconf.enable import enable

@click.command()
@click.option('--disable', '-d', default=False, is_flag=True,
              help='disable rather than enable the specified resources')
@click.option('--system_name', '-s', type=str, default='',
              help='Name of system to manipulate if not specified the first '
              'system found in the database will be used')
@click.argument('oksfile')
@click.argument('resource', required=True, nargs=-1)
def oks_enable(oksfile, disable, resource, system_name):
  """Script to enable or disable (-d) Resources from the first System of the
  specified OKS database file"""
  enable(oksfile, disable, resource, system_name)

if __name__ == '__main__':
  oks_enable()
