#!/bin/env python3

import click
from daqconf.enable_tpg import enable_tpg

@click.command()
@click.option('--exclude', '-d', default=False, is_flag=True,
              help='exclude rather than include the specified resources')
@click.option('--session_name', '-s', type=str, default='',
              help='Name of session to manipulate if not specified the first '
              'session found in the database will be used')
@click.argument('oksfile')
def oks_enable(oksfile, exclude, session_name):
  """Script to include or exclude (-d, for old terminology disabled) TP generation from the 
Session of the specified OKS database file"""
  enable_tpg(oksfile, exclude, session_name)

if __name__ == '__main__':
  oks_enable()
