#!/bin/env python3

import click
from daqconf.include_tpg import include_tpg

@click.command()
@click.option('--exclude', '-d', default=False, is_flag=True,
              help='exclude rather than include the specified excludable entities')
@click.option('--session_name', '-s', type=str, default='',
              help='Name of session to manipulate if not specified the first '
              'session found in the database will be used')
@click.argument('oksfile')
def oks_include(oksfile, exclude, session_name):
  """Script to include or exclude (-d, for the old name disabled) TP generation from the 
Session of the specified OKS database file"""
  include_tpg(oksfile, exclude, session_name)

if __name__ == '__main__':
  oks_include()
