#!/bin/env python3
import click

from  daqconf.validate import validate_session

@click.command()
@click.option('--session_name', '-s', type=str, default='',
              help='Name of session to validate if not specified the first '
              'session found in the database will be used')
@click.argument('oksfile')
def do_validate(oksfile, session_name):
    validate_session(oksfile, session_name)

if __name__ == '__main__':
    do_validate()
