#!/bin/env python3
import click

from  daqconf.validate import validate_system

@click.command()
@click.option('--system_name', '-s', type=str, default='',
              help='Name of system to validate if not specified the first '
              'system found in the database will be used')
@click.argument('oksfile')
def do_validate(oksfile, system_name):
    validate_system(oksfile, system_name)

if __name__ == '__main__':
    do_validate()
